import react from "react";
import "../stylesheets/TermsAndConditions.css";

function TermsAndConditions() {
    return (
        <div className="Terms-container">
            <h1>Terms and Conditions of Use</h1>
            <section>
                <h2>I.	ACCEPTANCE OF TERMS OF USE AND OTHER POLICIES</h2>
                <section>
                    <dl>
                        <dt><strong>The person who accesses.</strong></dt>
                        <dd><p>uses, and/or engages in any way in the Danta Sports Platform (as defined below) is referred to as "you" or "your" whenever appropriate ("Users"). You affirm and guarantee that you have the power to bind an entity if you utilize the Danta Sports Platform on that entity's behalf. "You" and "your" here refer to the entity you represent, and your acceptance of the Terms of Use will be considered an acceptance by that entity.</p></dd>

                        <dt><strong>Conditions of Use.</strong></dt>
                        <dd><p>Your use of our website, <a href="https://dantasports.com">https://dantasports.com</a> (the "Website"), our Danta Sports app for mobile and portable devices (the "App"), as well as any assignees and authorized licenses thereof, is governed by these terms of use (the "Terms of Use").The "Danta Sports Platform" refers to both the website and the app. Currently, Danta Sports Pvt. Ltd. ("Danta Sports"), a business established under the Companies Act of 2013, owns and runs the Danta Sports Platform. Its registered office is located at No. 13 & 14, Sy No. 151, Neeladri Nagar, Electronics City, Bangalore, Karnataka, India. Here, "we," "us," and "our" refer to Danta Sports as well as our partners, associates, successors, and authorized assignee. Before using the Danta Sports Platform, please carefully read these Terms of Use, which outline your rights, responsibilities, and limitations regarding your participation in the platform and use of its services (collectively referred to as the "Services"). Between you and Danta Sports, these Terms of Use and Privacy Policy (as defined below) form a binding contract. Clicking "I have read and agree to the terms of use" after installing, downloading, or even just using the Danta Sports Platform will create a legally binding agreement to abide by the Terms of Use and other Danta Sports policies (including but not limited to the Privacy Policy) that are posted on the Danta Sports Platform from time to time. These terms take effect on the date that you download, install, or use the Services.You are not permitted to access or use the Danta Sports Platform if you disagree with the aforementioned; therefore, you should not click to confirm your agreement. Please stop using or participating in the services provided by the Danta Sports Platform right away if you disagree with any of the terms outlined in the documents. You acknowledge that the terms, conditions, and disclaimers outlined in these Terms of Use are acceptable by using the Danta Sports Platform.</p></dd>

                        <dt><strong>Policy on Privacy.</strong></dt>
                        <dd><p>Users are informed about the collection and storage of their information ("User Content") by Danta Sports' privacy policy ("Privacy Policy"). As mentioned above, the Privacy Policy is now part of the stated Terms of Use. The Privacy Policy, found at <a href="https://dantasports.com/privacy">https://dantasports.com/privacy</a>,governs how you use the Danta Sports Platform.</p></dd>

                        <dt><strong>alterations to the terms of use.</strong></dt>
                        <dd><p>Any changes may be made at any time to these Terms of Use and any other document that is referenced. By publishing updates on its website at <a href="https://dantasports.com/terms">https://dantasports.com/terms</a>, Danta Sports maintains the right to alter these Terms of Use and other Danta Sports policies at any time. It is always your responsibility to keep an eye on the Terms of Use and other Danta Sports regulations, as well as to take notice of any updates made on the Danta Sports Platform. A 'pop up' will show on your screen to notify you of any changes Danta Sports proposes to the Terms of Use.It is anticipated that you will read the updated term or terms and give your approval. Your current registration will also be terminated if you don't accomplish this.</p></dd>

                    </dl>
                </section>
                <section>
                    <h2>II.	USE OF PLATFORM AND SERVICES</h2>
                    <p>Conditions for qualifying for membership.</p>
                    <section>
                        <p>To visit and see the Danta Sports Platform, you do not need to register with Danta Sports; but, in order to access and use any of its features, you will need to create a password-protected account ("Account"). You must create a password and provide your name, email address, and/or mobile number on the Danta Sports Platform's account registration page or screen in order to create an account. Additionally, you will have the option to enter extra optional information, which is not necessary to create an account but could help Danta Sports give you a more personalized experience when using the Danta Sports Platform.You can also create an account with your current login information from Facebook, Google, Twitter, or any other similar platform (your "Third-Party Site Account"). The term "Registered User" is occasionally used to refer to an account holder on the Danta Sports Platform.</p>
                        <p>Only those who are able to enter into legally enforceable contracts under the applicable laws may use the Danta Sports Platform. You affirm, acknowledge, and agree that you are at least eighteen years old, that all of the information you provide during registration is true and accurate, that you will keep it that way, and that using the Danta Sports Platform and its services does not contravene any applicable laws or regulations. If we determine that you are under the age of eighteen or that you are not abiding by any applicable laws, rules, or regulations, we may immediately terminate your account. Additionally, if you visit the Danta Sports Platform while under the legal age limit, please be advised that it will be presumed that your usage was approved by your parent or legal guardian and that they have monitored your use.</p>
                        <p>Your account and access to the services may be suspended or terminated at our discretion. (i) if any User Content you submitted during the registration process or later turns out to be erroneous, outdated, or lacking; (ii) if it is thought that your actions could put you, other Users, or us in legal hot water; and/or (iii) if you are discovered to be in violation of these Terms of Use.</p>
                        <p style={{ fontWeight: 'bold' }}>
                            It is your responsibility to keep your password secure. You acknowledge that you are solely responsible for any activity or acts under your account and that you will not share your password with any outside parties. If there is a security breach or any unauthorized use of your account, you must tell Danta Sports right away. Likewise, you must never use someone else's account without Danta Sports's prior approval. You pledge not to pose as another user of the Danta Sports Platform or to misrepresent yourself. By using your account without authorization, you hereby explicitly accept and agree that you will be responsible for any losses or damages (direct or indirect) that are incurred by Danta Sports, you, or anybody else.
                        </p>
                        <p>Utilizing the Platform. You acknowledge, accept, and agree that the following legally enforceable guidelines will strictly control how you use the Danta Sports Platform.</p>
                        <p>You are not allowed to host, display, upload, download, alter, publish, transmit, update, or distribute any information that: belongs to someone else and that you are not authorized to access.</p>
                        <p>The content may be blasphemous, defamatory, obscene, pornographic, paedophilic, libellous, slanderous, criminally inciting or invading another person's privacy, hateful, racially or ethnically objectionable, disparaging, relating to or encouraging money laundering or gambling, or unlawfully threatening or unlawfully harassing, including but not limited to any content that violates the Indian Penal Code, 1860.</p>
                        <p>is in any way deceptive or misrepresentative; contains content that is obviously offensive to the online community, such as sexually explicit content, or content that encourages obscenity, paedophilia, racism, bigotry, hatred, or physical harm of any kind against any group or individual; harasses or encourages harassment of another person; involves sending "junk mail," "chain letters," or unsolicited mass mailing or "spamming"; encourages unlawful behavior or conduct that is abusive, threatening, obscene, defamatory, or libellous; infringes upon or violates the rights of any third party [including, but not limited to, intellectual property rights, rights of privacy (including without limitation unauthorized disclosure of a person's name, email address, physical address, or phone number), or rights of publicity].</p>
                        <p>contains restricted or password-only access pages, or hidden pages or images (those not linked to or from another accessible page); offers content that exploits people in a sexual, violent, or otherwise inappropriate manner, or requests personal information from anyone; encourages the illegal or unauthorized copying of another person's copyrighted work (see "copyright complaint" below for instructions on how to file a complaint about uploaded copyrighted material); provides pirated computer programs or links to them, or offers information to get around manufacturer-installed copy-protect devices</p>
                        <p>contains video, photographs, or images of another person (with a minor or an adult); attempts to obtain unauthorized access or goes beyond the scope of authorized access to the Danta Sports Platform or to profiles, blogs, communities, account information, bulletins, friend requests, or other areas of the Danta Sports Platform; requests passwords or personal identifying information from other Users for commercial or unlawful purposes; engages in commercial activities and/or sales without our prior written consent, such as contests, sweepstakes, barter, advertising, pyramid schemes, or the purchase or sale of goods related to the Danta Sports Platform.Throughout these Terms of Use, "Danta Sports' prior written consent" refers to a communication from the company's legal department or authorized representative that specifically addresses and permits the activity or conduct for which you have requested authorization; solicits gambling or engages in any gambling activity that is or could be interpreted as illegal; interferes with another user's use of the Danta Sports Platform or any third-party user's enjoyment of similar services; refers to any website or URL that, in our sole discretion, contains content that would be prohibited or violates the letter or spirit of these Terms of Use</p>
                        <p>harm children in any way; violate any currently enacted laws; violate any patent, trademark, copyright, or other intellectual property rights; violate third parties' trade secrets, rights to publicity, or rights to privacy; misleads or deceives the addressee or users about the source of such messages; or transmits any information that is egregiously offensive or threatening in nature</p>
                        <p>contain any computer code, files, or programs intended to disrupt, destroy, or restrict the operation of any computer resource; contain software viruses; or contain trojan horses, worms, time bombs, cancelbots, easter eggs, or other computer programming routines that may damage, interfere negatively with, lower the value of, covertly intercept, or expropriate any system, data, or personal information; endanger India's unity, integrity, defense, security, or sovereignty; jeopardize public order; incite criminal activity, obstruct the investigation of any criminal activity, or offend any other country; directly or indirectly offer, attempt to offer, trade, or attempt to trade in any item whose dealing is prohibited or restricted in any way by the provisions of any applicable law, rule, regulation, or guideline currently in effect;or makes us liable or results in the loss of our internet service provider's or
                            other suppliers' services, either completely or partially.
                        </p>
                        <p>You are not allowed to use the Danta Sports Platform for any automated or systematic data collecting activities (such as scraping, data mining, data extraction, data harvesting, 'framing' (iframes), or article'spinning') without Danta Sports's express written approval.
                        </p>
                        <p>You must not access, acquire, copy, or monitor any part of the Danta Sports Platform or its content using any "deep-link," "page-scrape," "robot," "spider," or other automatic device, program, algorithm, or methodology, or any similar or equivalent manual process. You must also not reproduce or circumvent the navigational structure or presentation of the Danta Sports Platform or its content in any way. Finally, you must not attempt to obtain any materials, documents, or information through any means that are not specifically made available through the Danta Sports Platform. We maintain the right to forbid any such behavior.</p>
                        <p>You must refrain from using hacking, "password mining," or any other illegal method to try to obtain unauthorized access to any part or feature of the Danta Sports Platform, any other systems or networks linked to the Danta Sports Platform, or to any server, computer, network, or service provided on or through the Danta Sports Platform</p>
                        <p>It is forbidden to investigate, scan, or test the Danta Sports Platform or any network that is linked to it, or to violate any of the security or authentication protocols on the Danta Sports Platform or any network that is connected to it. You are not allowed to reverse lookup, trace, or attempt to trace any information about another user, visitor, or buyer on the Danta Sports Platform, including any account on the platform that is not yours, to its source, or take advantage of the Danta Sports Platform or any information provided by or through the Danta Sports Platform in any way that would reveal any information.Other than your personal information as permitted by the Danta Sports Platform, this includes but is not limited to personal identification or information.</p>
                        <p>It is forbidden for you to say or do anything that could harm Danta Sports's reputation or image on the Danta Sports Platform, or to damage or dilute any of the company's trade or service marks, trade name, or goodwill associated with those trade or service marks that we may own or use. This includes talking negatively about us or the brand name or domain name that we use, including the name "Danta Sports."</p>
                        <p>You promise not to try to or actually use any equipment, program, or routine to impede the correct operation of the Danta Sports Platform, any transactions that are taking place on it, or the usage of the Danta Sports Platform by anybody else.</p>
                        <p>In order to conceal the origin of any message or transmittal you submit to us via the Danta Sports Platform or any service provided on or through the Danta Sports Platform, you are not permitted to forge headers or otherwise alter identifiers. It is forbidden to impersonate any other person or thing or to act as though you are or represent someone else</p>
                        <p>You are not permitted to use the Danta Sports Platform or the Danta Sports Platform for any purpose that is forbidden by these Terms of Use, or to encourage the commission of any illegal action or other activity that violates the rights of Danta Sports or third parties.</p>
                        <p>The Information Technology Act, 2000, India and its regulations, as well as all other applicable domestic laws, rules, and regulations (including the provisions of any applicable exchange control laws or regulations in force), must always be fully complied with by you.and (c) laws pertaining to international transactions, foreign currency rules, statutes, ordinances, and regulations (such as income tax, goods and service taxes, and local levies) that affect how you use our services, as well as how you list, buy, and solicit offers to utilize our services. You must refrain from transacting in any goods or services that are forbidden by the terms of any applicable laws, including exchange control legislation or regulations that are currently in effect.</p>
                        <p>You agree to give us the non-exclusive, worldwide, perpetual, irrevocable, royalty-free, sub-licensable (through multiple tiers) right to exercise the copyright, publicity, database rights, or any other rights you may have in your information, in any media now known or not currently known, so that we can use the User Content you provide without infringing on your rights or breaking any laws. Your information will only be used in compliance with the Privacy Policy and these Terms of Use, which apply to using the Danta Sports Platform.
                        </p>
                        <p>We will keep an eye on your interactions and messages on the Danta Sports Platform, and if you engage in any kind of solicitation or advertising, we reserve the right to limit how many emails or messages a user can send to other users in a 24-hour period, based on our sole discretion. You are aware that in order to comply with any law, regulation, or legitimate government request, we may at any time disclose any information (including the identities of the people supplying information or materials on the Danta Sports Platform). This could involve sharing the information in the course of looking into suspected unlawful behavior or encouraging illegal activity, among other things. or in reaction to a valid subpoena or court order. Furthermore, in the course of investigating and/or resolving potential crimes, particularly those that may involve personal injury, we may (and you hereby expressly authorize us to) disclose any information about you to law enforcement or other government officials as we, in our sole discretion, deem necessary or appropriate.</p>
                        <p>Although we are under no need to do so, we reserve the right to keep an eye on the content that is uploaded on the Danta Sports Platform. Any content that, in its sole judgment, contravenes or is suspected of violating any relevant legislation or the word or spirit of these Terms of Use may be removed or edited by Danta Sports. Despite this right, you are still entirely in charge of the information you include in your private chats and on the Danta Sports Platform. Please be aware that Danta Sports may not always agree with the content posted. Danta Sports will never take responsibility for or be liable for any content that is placed on the Danta Sports Platform, or for any claims, losses, or damages that may arise from using or viewing such content. You hereby declare and guarantee that you are the owner of all the rights to the content you supply and the information it contains, and that it will not violate any third-party's property or other rights or contain any information that is libellous, tortious, or otherwise illegal.</p>
                        <p>Any communication or business transactions you have with or engage in on or through the Danta Sports Platform with advertisers, including payment and delivery of related goods or services, as well as any other terms, conditions, warranties, or representations related to such transactions, are exclusively between you and the advertiser. Any loss or harm of any kind resulting from these transactions or from the existence of such advertisers on the Danta Sports Platform will not be our responsibility or liability. Please be aware that Danta Sports makes no guarantees regarding the caliber or functionality of any goods or services hosted on the Danta Sports Platform. Customers are urged to use their own judgment when selecting any of the goods or services offered on the Danta Sports Platform.</p>
                        <p>On the Danta Sports Platform, other users (including unauthorized users or "hackers") may publish or transmit offensive or obscene content, and you might unintentionally come into contact with such content. Additionally, by using the Danta Sports Platform, you run the risk of giving someone access to personal information about you, which they could then use to harass or harm you. Although we disapprove of such unlawful uses, by using the Danta Sports Platform, you understand and accept that we have no control over how any personal information you share with others or publicly reveal is used. Please choose carefully what information you share with others or publicly reveal on the Danta Sports Platform.</p>
                    </section>
                </section>
                <section>
                    <h2>III.	TERMS OF SERVICE</h2>
                    <section>
                        <p>You understand and agree that third-party providers ("Service Providers") offer goods, services, events, and arenas through Danta Sports, and that Danta Sports does not: Provide any express or implied guarantees regarding the caliber of the goods, services, events, or arenas provided by the Service Providers;
                            Endorse or attest to the fact that a particular product or products, services, events, or arenas that the service provider offers or provides meet a given standard of quality or have been evaluated in a particular way</p>
                        <p>assume all liability in the event that the service provider's goods, services, events, or arenas fall short of the user's expectations or if the user experiences any loss or harm—including physical harm—as a result of using these items; </p>
                        <p>assume all liability in the event that the service provider modifies, alters, amends, or replaces the goods, services, events, or arenas.</p>
                        <p>When making a payment, you could be asked to give the authorized payment gateways your credit or debit card information. In order to use the services, you consent to giving the authorized payment gateways your true and accurate credit or debit card information. You must use your own credit or debit card for all transactions; you are not allowed to use one that is not legally yours. Unless necessary for fraud verifications or as mandated by law, regulation, or court order, the information you supply will not be used or shared with any third parties. The confidentiality and security of your credit/debit card information will be entirely your responsibility.We specifically disclaim any liability that might result from using your credit or debit card without authorization.</p>
                        <p>The Danta Sports Platform lacks the necessary tools and authorization to complete any kind of financial transaction. The payment gateway must be used for all payments. Danta Sports will transfer funds to the service provider via the payment gateway or another approved payment method. The service provider will give you a receipt for the payment directly. Please make sure you submit a claim to the service provider for an invoice.</p>
                        <p>None of the service providers are recommended by us. Furthermore, even though you must give accurate information in accordance with these Terms of Use, we make no effort to verify whether the information is true or not.
                        </p>
                        <p>You consent to refrain from attempting to hold us legally responsible for any acts or inactions of the Service Provider or to pursue any legal remedies against us.</p>
                    </section>
                </section>

                <section>
                    <h2>IV.	GENERAL TERMS OF USE</h2>
                    <section>
                        <p>There will be no reimbursement for payments made via the Danta Sports Platform for any reason, including not using or buying any goods, services, events, or arenas.</p>
                        <p>Regular updates will be made to the data provided by the Danta Sports Platform, pending feedback from the service provider. If a product, service, venue, or arena is changed, withdrawn, or amended by the service provider and is not updated on the Danta Sports Platform when the user is using it, the service provider is responsible for making sure that the products, services, events, or arenas are replaced with comparable offerings or for returning the user's money.</p>
                        <p>You are responsible for keeping your password, user ID, and any other information we may give you as part of our security protocols private and not sharing it with anyone or anything other than us if you decide to use the Danta Sports Platform. If you have not complied with any of the terms of use, we have the right to disable your password or user identification code at any time and at our sole discretion.</p>
                        <p>In a few Indian cities, the Danta Sports Platform can be used to buy or access goods, services, events, or arenas. Only Service Providers who have registered on the Danta Sports Platform will be able to access and use the platform. Since we only offer our services in a few Indian cities, we have complied with all applicable Indian regulations in order to provide you with access to the Danta Sports Platform and its content. You assume full responsibility if you access the Danta Sports Platform from outside of India or our operational zones.The Danta Sports Platform and its contents are not guaranteed to be accessible or appropriate for usage outside of specific cities. You are in charge of the consequences and making sure that all applicable laws, rules, bylaws, licenses, registrations, permits, authorizations, and guidelines are followed if you decide to access or use the Danta Sports Platform from or in places outside of specific cities.</p>
                        <p>You will always be in charge of using the Services on your computer or mobile device and making sure that everyone who accesses the Danta Sports Platform on your computer or mobile device is aware of these Terms of Use and Danta Sports regulations.</p>
                        <p>
                            You acknowledge and agree that using the Services does not require having a computer, mobile device, or other piece of equipment. Additionally, you are aware that using the Danta Sports Platform necessitates having telecommunications and internet access. Under no circumstances will we be held accountable or liable for the charges you incur in order to access and use the Danta Sports Platform and take use of the services.
                        </p>
                        <p>You consent to receiving transactional and promotional emails and SMS from Danta Sports or its affiliated partners.
                            By using the Danta Sports Platform, you affirm and guarantee that: All of the information you provide during registration is true, legal, and correct, and that you promise to keep it that way.
                        </p>
                        <p>You acknowledge that you are solely responsible for all content published or displayed through your account, including any email messages, and your interactions with other users. You also agree to abide by all applicable local, state, federal, and international laws, treaties, and regulations, including those pertaining to data privacy, international communications, and the transmission of technical or personal data. You will only use the Danta Sports Platform for your own personal use, and you will not permit others to use your account, including your profile or email address.</p>
                        <p>All trademarks, copyrights, patents, trade secrets, privacy and publicity rights, and/or other proprietary rights contained in any content that you submit, post, upload, distribute, or otherwise transmit or make available are yours, and you are the sole owner of all necessary licenses, consents, permissions, and rights. No payment is required, nor is any other party or entity required to grant permission or authorization</p>
                        <p>You specifically waive any claims you may have in this regard under any applicable Indian laws and agree to release and fully indemnify Danta Sports and/or any of its directors, shareholders, officers, and representatives from any expense, damage, liability, or other consequence of any of the actions of the users of the Danta Sports Platform. In addition, you acknowledge that Danta Sports' officers, employees, agents, subsidiaries, successors, assignee, and subcontractors will all be protected by the restrictions and disclaimers outlined in these Terms of Use.</p>
                        <p>Despite its best efforts, Danta Sports is unable to control or assume responsibility for the information that other users submit and make public on the Danta Sports Platform. Information from other users may offend, hurt, be inconsistent, erroneous, or misleading to you. When utilizing the Danta Sports Platform, please exercise caution and follow safe trading procedures.</p>
                    </section>
                </section>
                <section>
                    <h2>V.	ACCESS TO THE PLATFORM, ACCURACY AND SECURITY</h2>
                    <section>
                        <p>We work hard to ensure that the Danta Sports Platform is accessible at all times. We do not, however, guarantee that the Danta Sports Platform will be available without interruption, on time, without errors, or free of viruses or other dangerous elements, nor do we guarantee that these flaws will be fixed.</p>
                        <p>The Danta Sports Platform's compatibility with all of your chosen hardware and software is not guaranteed by us. If you download, install, access, or use the Danta Sports Platform, or if you get any content from it, we won't be responsible for any damage to, or viruses or other code that may affect, any equipment (including but not limited to your mobile device), software, data, or other property. through the use of the Danta Sports Platform. Furthermore, we will not be held responsible for the conduct of other parties.
                            The accuracy, correctness, and reliability of the information on the Danta Sports Platform are not guaranteed by us.
                        </p>
                        <p>We retain the right to temporarily or permanently deny you or any other user access to the Danta Sports Platform at any time and without prior notice.</p>
                    </section>
                </section>
                <section>
                    <h2>VI.	RELATIONSHIP WITH OPERATORS IF THE PLATFORM IS ACCESSED ON MOBILE DEVICES</h2>
                    <section>
                        <p>If the Danta Sports Platform is accessed via a mobile device, it is not connected to, sponsored by, or endorsed by any operator, including but not limited to Apple, Google, Android, or RIM Blackberry (each of which is referred to as a "Operator").</p>
                        <p>The Operator's terms and conditions also apply to your download, installation, access, and use of the Danta Sports Platform.</p>
                        <p>To the degree that these Terms of Use specify, you and we both understand that these Terms of Use are made exclusively between us and you, not with any Operators, and that we alone are in charge of the Danta Sports Platform and its content.</p>
                        <p>Your license for the Danta Sports Platform is restricted to using it on a mobile device that you own or control, as allowed by these Terms of Use, and is not transferable.</p>
                        <p>Any maintenance and support services pertaining to the Danta Sports Platform that are mandated by relevant law are entirely our responsibility. Both you and we agree that an operator is under no duty to provide any upkeep or support services for the Danta Sports Platform.</p>
                        <p>Both you and we agree that we, not the relevant Operator, are in charge of handling any claims made by you or any third party about the Danta Sports Platform, your possession of it, or how you use it. These claims may include, but are not limited to: (i) any allegation that the Danta Sports Platform does not comply with any applicable legal or regulatory requirements; and (ii) claims arising under consumer protection or comparable laws.</p>
                        <p>You and we both agree that we, and not the relevant Operator, will be solely liable for the investigation, defense, settlement, and discharge of any third-party claim alleging that the Danta Sports Platform or your use of it violates that third party's intellectual property rights</p>
                        <p>The relevant Operator and its subsidiaries are third-party beneficiaries of these Terms of Use, and you and we both understand and agree that they have the right—and will be presumed to have accepted the right—to enforce these Terms of Use against you as a third-party beneficiary after you accept them.</p>
                    </section>
                </section>
                <section>
                    <h2>VII.	DISCLAIMERS</h2>
                    <section>
                        <p>Certain elements and capabilities of the Danta Sports Platform might not be completely functional due to ongoing improvements.</p>
                        <p>There may be delays, omissions, or inaccuracies in the content offered on the Danta Sports Platform, as well as delays or errors in the platform's functionality, because of the whims of electronic information distribution and the limitations that come with presenting information gathered from multiple sources. Therefore, we make no guarantees that the information given is accurate in every situation.</p>
                        <p>We specifically disclaim any liability that might result from using credit or debit cards without authorization.</p>
                        <p>You understand that the Danta Sports Platform offers services from third parties. In order to make it easier for us to provide you with specific services, we may occasionally have partnered or partnered with some of these third parties. However, you understand and agree that we never make any claims or representations about the services of any third party, and we will not be held accountable to you or any third party for any claims or consequences resulting from or related to such third party, including but not limited to any liability or responsibility for any death, injury, or impairment that you or any third party may experience.Any rights and claims you may have against us for services provided by third parties are hereby disclaimed and waived.</p>
                        <p>Danta Sports makes no representations or warranties on the item-specifics (such as legal title, creditworthiness, identity, etc.) of any of the Users, with the exception of a quick background check. It is recommended that you exercise your best judgment when dealing with any user on the Danta Sports Platform and independently confirm their legitimacy.</p>
                        <p>Although the content on the Danta Sports Platform was created to give accurate information about the topic covered, it is provided with the understanding that we expressly and implicitly make no guarantees, representations, or warranties of any kind regarding the professional qualifications, expertise, caliber of work, or other information contained herein. Furthermore, none of the services sold or represented here are in any way endorsed by us. We will never be responsible to you or any other person for any choices you make or actions you take based on this information.</p>
                        <p>The information that follows is given "as is" Regarding the timeliness, substance, sequence, correctness, efficacy, or completeness of any information or data given hereunder, as well as the possibility that the information or data may be relied upon, neither we nor our employees offer any warranties or representations. Multiple responses from various sources may typically be made available, and users are free to use, adapt, modify, or alter suggestions based on their unique circumstances. They can also use suggestions in conjunction with other sources they may have, which releases us and our consultants, business associates, affiliates, business partners, and employees from any professional liability.</p>
                        <p>For any losses or injuries resulting from or connected to the information or services offered on the Danta Sports Platform, we will not be held accountable to you or anybody else. In this sense, you agree that the Danta Sports Platform's services include activities that are inherently risky. However, we only offer a booking platform to make such activities possible, and neither us nor our staff, affiliates, writers, or agents will ever be held accountable to you or any other third party for any choices you make or actions you take as a result of using the services provided here.</p>
                        <p>Whether based on a warranty, contract, tort, or other legal theory, and whether or not we are informed of the possibility of such damages, we will never be held responsible for any damages (including, but not limited to, direct, indirect, incidental, special, consequential, or exemplary damages, damages resulting from personal injury or wrongful death, and damages resulting from lost profits, lost data, or business interruption) resulting from any services provided by any third party through the Danta Sports Platform. However, at our sole discretion, we shall make an effort to reimburse the User for any money they may have paid, and our liability in this regard, if any, will be restricted to the User's payment for the specific booking on the Danta Sports Platform.</p>
                        <p>Anything that would make it illegal or unlawful for Danta Sports to exclude or limit, or to attempt or purport to exclude or limit, its liability is not covered by these disclaimers. This includes death or personal injury brought on by the negligence of its agents or employees, fraud or fraudulent misrepresentation by its agents or employees, and any other matter.</p>
                        <p>No advice of any sort is contained in or intended to be contained in these Terms of Use. You should speak with a qualified expert if you need guidance on any legal, financial, or medical issue.</p>
                    </section>
                </section>
                <section>
                    <h2>VIII.	BREACH OF TERMS</h2>
                    <section>
                        <p>You agree that Danta Sports, at its sole and absolute discretion, may, but is not required to, immediately and without notice, terminate your access to or participation in the use of the Danta Sports Platform (or any part of it), delete, terminate, or deactivate your account, block your email address or IP address, or remove and discard any content on the Danta Sports Platform ("Termination"), for any reason, including but not limited to, if Danta Sports believes or has reason to believe that you have violated any of the Terms of Use.</p>
                        <p>You agree to indemnify and hold Danta Sports harmless from any losses, damages, costs, liabilities, and expenses (including, but not limited to, legal fees and any sums paid to a third party in the settlement of a claim or dispute) that it may incur or suffer as a result of any violation of these Terms of Use by you or from any allegation that you have violated any of these Terms of Use.</p>
                        <p>Consequences of termination.</p>
                        <p>Your ability to use the Danta Sports Platform will automatically end when your account is terminated. You understand and accept that your ability to utilize the Danta Sports Platform as intended, your compliance with the Terms of utilize, the ongoing activation of your Account, and your authorized participation in the Danta Sports Platform are all prerequisites for receiving any services under this agreement. The Danta Sports system may still include leftover data despite the aforementioned.</p>
                        <p>If you gave a working email address when you registered, Danta Sports will send you an email informing you of any termination or cancellation. This notification will take effect as soon as Danta Sports delivers it.</p>
                        <p>All copies of Danta Sports data and other content in your custody or control must be destroyed right once upon termination. Additionally, you understand and agree that Danta Sports will not be responsible for any termination of your access to the Danta Sports Platform, either to you or to any third party. Any information gathered from your use of the Danta Sports Platform may be used by Danta Sports for internal analysis and archive reasons after your service is terminated. Danta Sports is under no obligation to give you back any content you have provided. Terms of Use provisions pertaining to termination, intellectual property, dispute resolution, indemnity, limitations of liability, and the treatment of user and third-party material will remain in effect even after the terms of use expire or are terminated of the Danta Sports Platform and/or your Account.</p>
                        <p>You consent to indemnify and hold harmless Danta Sports, its officers, managers, Registered Users, affiliates, successors, assignees, directors, agents, suppliers, and employees from any claim or demand made by any third party as a result of or arising out of such termination, including reasonable legal fees and court costs.</p>
                        <p>Users who have been suspended or terminated may be reinstated at any time at our sole discretion. Until they are restored by us, a terminated user is not permitted to register, attempt to register, or use the Danta Sports Platform in any way.</p>
                    </section>
                </section>
                <section>
                    <h2>IX.	INTELLECTUAL PROPERTY</h2>
                    <section>
                        <p>
                            Our rights to use the Danta Sports Platform and its content are either non-exclusive, global, perpetual, irrevocable, royalty-free, and sub-licensable (through several tiers) or we are the owners of intellectual property rights.
                        </p>
                        <p>You can download excerpts and print one copy of any page, file, or other content from the Danta Sports Platform for your own use. You can also share the content on the Danta Sports Platform with other people in your organization.</p>
                        <p>You are not permitted to redistribute any content from the Danta Sports Platform. If Danta Sports has made it clear that some content is available for redistribution, you may only do so within your company and in accordance with Danta Sports's intentions.</p>
                        <p>You are not permitted to exhibit content from the Danta Sports Platform in public or reprint it on any other print or digital media platform. Additionally, you are prohibited from using iframes or screenscrapers to republish or replicate any content from the Danta Sports Platform.</p>
                        <p>Any materials you have downloaded or printed from the Danta Sports Platform cannot be altered or altered, and you are not permitted to use any graphics, photos, videos, or audio clips apart from the text that goes with them.</p>
                        <p>Without a license from us or our licensors, you are not permitted to use, reproduce, duplicate, copy, sell, sublicense, or rent out any portion of the content on the Danta Sports Platform for profit.</p>
                        <p>Your right to use the Danta Sports Platform will be immediately terminated if you print off, copy, or download any portion of it in violation of these Terms of Use. You will also be required to return or delete any copies of the materials you have created, at our discretion.</p>
                    </section>
                </section>
                <section>
                    <h2>X.	TREATMENT OF USER CONTENT</h2>
                    <p>We process User Content to us in accordance with our Privacy Policy available at <a href="https://dantasports.com/privacy">https://dantasports.com/privacy</a> </p>
                </section>
                <section>
                    <h2>XI.	THIRD PARTY CONTENT</h2>
                    <section>
                        <p>As between you and us, you hereby bear all risk of harm or injury resulting from any such noncompliance. We cannot and will not guarantee that other Users are or will be adhering to the aforementioned regulations or any other elements of these Terms of Use.</p>
                        <p>You understand that when you click on a link that takes you outside of the Danta Sports Platform, you are entering a website that is not under our control and may have different terms of use and privacy policies. By evaluating links to other websites, you agree that we have no control over them. Although we are not required to do so, we reserve the right to remove links to and/or from third-party websites to the Danta Sports Platform.</p>
                    </section>
                </section>
                <section>
                    <h2>XII.	SEVERABILITY</h2>
                    <p>The remaining Terms of Use shall survive, remain in full force and effect, and continue to be binding and enforceable, and any term that is found to be illegal, invalid, or otherwise unenforceable under the laws of any state or nation in which these Terms of Use are intended to be effective shall be severed and deleted to the extent and within the jurisdiction where such term is illegal, invalid, or unenforceable.</p>
                </section>
                <section>
                    <h2>XIII.	ASSIGNMENT</h2>
                    <p>Danta Sports may assign, transfer, subcontract, or pretend to assign, transfer, or subcontract its duties under these Terms of Use to any other individual or organization at any time, at its sole discretion. Nevertheless, you are not permitted to assign, transfer, or subcontract your responsibilities under these Terms of Use to any other organization or individual, nor should you pretend to do so.</p>
                </section>
                <section>
                    <h2>XIV.	GOVERNING LAW AND DISPUTE RESOLUTION </h2>
                    <p>The laws of India apply to these Terms of Use. The courts in Bangalore, India, will have jurisdiction over any action, suit, or other legal proceeding that is started to settle any dispute originating under or connected to the Danta Sports Platform or these Terms of Use.</p>
                </section>
                <section style={{ marginBottom: "50px" }}>
                    <h2>XV.	CONTACT US</h2>
                    <p>Please contact us for any questions or comments regarding the Terms of Use and other policies governing the Danta Sports Platform by e-mail at <a href="mailto:contact@dantasports.com" target="_blank" rel="noopener noreferrer">contact@dantasports.com</a></p>
                </section>
            </section>
        </div>
    )
}

export default TermsAndConditions;